# Generated by Django 2.0 on 2017-12-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_directory', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='subjectname',
            name='output_directory',
        ),
    ]
