# Generated by Django 2.0 on 2017-12-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20171208_0537'),
    ]

    operations = [
        migrations.CreateModel(
            name='BIDSModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=100)),
                ('out_dir', models.CharField(max_length=200)),
                ('in_dir', models.CharField(max_length=200)),
                ('multi_sess_pass', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='OsirixModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=100)),
                ('out_dir', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='OutputDirectory',
        ),
        migrations.DeleteModel(
            name='SubjectName',
        ),
    ]
